export const countries = [
  {"id":"1","name":"Afghanistan","iso2":"AF","iso3":"AF","code":"93","flag":"🇦🇫"},
  {"id":"2","name":"Åland Islands","iso2":"AX","iso3":"ALA","code":"358","flag":"🇦🇽"},
  {"id":"3","name":"Albania","iso2":"AL","iso3":"AL","code":"355","flag":"🇦🇱"},
  {"id":"4","name":"Algeria","iso2":"DZ","iso3":"DZA","code":"213","flag":"🇩🇿"},
  {"id":"5","name":"American Samoa","iso2":"AS","iso3":"ASM","code":"1","flag":"🇦🇸"},
  {"id":"6","name":"Andorra","iso2":"AD","iso3":"AND","code":"376","flag":"🇦🇩"},
  {"id":"7","name":"Angola","iso2":"AO","iso3":"AGO","code":"244","flag":"🇦🇴"},
  {"id":"8","name":"Anguilla","iso2":"AI","iso3":"AIA","code":"1","flag":"🇦🇮"},
  {"id":"9","name":"Antarctica","iso2":"AQ","iso3":"ATA","code":"672","flag":"🇦🇶"},
  {"id":"10","name":"Antigua and Barbuda","iso2":"AG","iso3":"ATG","code":"1","flag":"🇦🇬"},
  {"id":"11","name":"Argentina","iso2":"AR","iso3":"ARG","code":"54","flag":"🇦🇷"},
  {"id":"12","name":"Armenia","iso2":"AM","iso3":"ARM","code":"374","flag":"🇦🇲"},
  {"id":"13","name":"Aruba","iso2":"AW","iso3":"ABW","code":"297","flag":"🇦🇼"},
  {"id":"14","name":"Australia","iso2":"AU","iso3":"AUS","code":"61","flag":"🇦🇺"},
  {"id":"15","name":"Austria","iso2":"AT","iso3":"AUT","code":"43","flag":"🇦🇹"},
  {"id":"16","name":"Azerbaijan","iso2":"AZ","iso3":"AZE","code":"994","flag":"🇦🇿"},
  {"id":"17","name":"Bahamas","iso2":"BS","iso3":"BHS","code":"1","flag":"🇧🇸"},
  {"id":"18","name":"Bahrain","iso2":"BH","iso3":"BHR","code":"973","flag":"🇧🇭"},
  {"id":"19","name":"Bangladesh","iso2":"BD","iso3":"BGD","code":"880","flag":"🇧🇩"},
  {"id":"20","name":"Barbados","iso2":"BB","iso3":"BRB","code":"1","flag":"🇧🇧"},
  {"id":"21","name":"Belarus","iso2":"BY","iso3":"BLR","code":"375","flag":"🇧🇾"},
  {"id":"22","name":"Belgium","iso2":"BE","iso3":"BEL","code":"32","flag":"🇧🇪"},
  {"id":"23","name":"Belize","iso2":"BZ","iso3":"BLZ","code":"501","flag":"🇧🇿"},
  {"id":"24","name":"Benin","iso2":"BJ","iso3":"BEN","code":"229","flag":"🇧🇯"},
  {"id":"25","name":"Bermuda","iso2":"BM","iso3":"BMU","code":"1","flag":"🇧🇲"},
  {"id":"26","name":"Bhutan","iso2":"BT","iso3":"BTN","code":"975","flag":"🇧🇹"},
  {"id":"27","name":"Bolivia","iso2":"BO","iso3":"BOL","code":"591","flag":"🇧🇴"},
  {"id":"28","name":"Bosnia and Herzegovina","iso2":"BA","iso3":"BIH","code":"387","flag":"🇧🇦"},
  {"id":"29","name":"Botswana","iso2":"BW","iso3":"BWA","code":"267","flag":"🇧🇼"},
  {"id":"30","name":"Bouvet Island","iso2":"BV","iso3":"BVT","code":"N\/A","flag":"🇧🇻"},
  {"id":"31","name":"Brazil","iso2":"BR","iso3":"BRA","code":"55","flag":"🇧🇷"},
  {"id":"32","name":"British Indian Ocean Territory","iso2":"IO","iso3":"IOT","code":"246","flag":"🇮🇴"},
  {"id":"33","name":"Brunei","iso2":"BN","iso3":"BRN","code":"673","flag":"🇧🇳"},
  {"id":"34","name":"Bulgaria","iso2":"BG","iso3":"BGR","code":"359","flag":"🇧🇬"},
  {"id":"35","name":"Burkina Faso","iso2":"BF","iso3":"BFA","code":"226","flag":"🇧🇫"},
  {"id":"36","name":"Burundi","iso2":"BI","iso3":"BDI","code":"257","flag":"🇧🇮"},
  {"id":"37","name":"Cambodia","iso2":"KH","iso3":"KHM","code":"855","flag":"🇰🇭"},
  {"id":"38","name":"Cameroon","iso2":"CM","iso3":"CMR","code":"237","flag":"🇨🇲"},
  {"id":"39","name":"Canada","iso2":"CA","iso3":"CAN","code":"1","flag":"🇨🇦"},
  {"id":"40","name":"Cape Verde","iso2":"CV","iso3":"CPV","code":"238","flag":"🇨🇻"},
  {"id":"41","name":"Caribbean Netherlands","iso2":"BQ","iso3":"BES","code":"599","flag":"🇧🇶"},
  {"id":"42","name":"Cayman Islands","iso2":"KY","iso3":"CYM","code":"1","flag":"🇰🇾"},
  {"id":"43","name":"Central African Republic","iso2":"CF","iso3":"CAF","code":"236","flag":"🇨🇫"},
  {"id":"44","name":"Chad","iso2":"TD","iso3":"TCD","code":"235","flag":"🇹🇩"},
  {"id":"45","name":"Chile","iso2":"CL","iso3":"CHL","code":"56","flag":"🇨🇱"},
  {"id":"46","name":"China","iso2":"CN","iso3":"CHN","code":"86","flag":"🇨🇳"},
  {"id":"47","name":"Christmas Island","iso2":"CX","iso3":"CXR","code":"61","flag":"🇨🇽"},
  {"id":"48","name":"Cocos (Keeling) Islands","iso2":"CC","iso3":"CCK","code":"61","flag":"🇨🇨"},
  {"id":"49","name":"Colombia","iso2":"CO","iso3":"COL","code":"57","flag":"🇨🇴"},
  {"id":"50","name":"Comoros","iso2":"KM","iso3":"COM","code":"269","flag":"🇰🇲"},
  {"id":"51","name":"Republic of the Congo","iso2":"CG","iso3":"COG","code":"242","flag":"🇨🇬"},
  {"id":"52","name":"DR Congo","iso2":"CD","iso3":"COD","code":"243","flag":"🇨🇩"},
  {"id":"53","name":"Cook Islands","iso2":"CK","iso3":"COK","code":"682","flag":"🇨🇰"},
  {"id":"54","name":"Costa Rica","iso2":"CR","iso3":"CRI","code":"506","flag":"🇨🇷"},
  {"id":"55","name":"Côte d'Ivoire (Ivory Coast)","iso2":"CI","iso3":"CIV","code":"225","flag":"🇨🇮"},
  {"id":"56","name":"Croatia","iso2":"HR","iso3":"HRV","code":"385","flag":"🇭🇷"},
  {"id":"57","name":"Cuba","iso2":"CU","iso3":"CUB","code":"53","flag":"🇨🇺"},
  {"id":"58","name":"Curaçao","iso2":"CW","iso3":"CUW","code":"599","flag":"🇨🇼"},
  {"id":"59","name":"Cyprus","iso2":"CY","iso3":"CYP","code":"357","flag":"🇨🇾"},
  {"id":"60","name":"Czechia","iso2":"CZ","iso3":"CZE","code":"420","flag":"🇨🇿"},
  {"id":"61","name":"Denmark","iso2":"DK","iso3":"DNK","code":"45","flag":"🇩🇰"},
  {"id":"62","name":"Djibouti","iso2":"DJ","iso3":"DJI","code":"253","flag":"🇩🇯"},
  {"id":"63","name":"Dominica","iso2":"DM","iso3":"DMA","code":"1","flag":"🇩🇲"},
  {"id":"64","name":"Dominican Republic","iso2":"DO","iso3":"DOM","code":"1","flag":"🇩🇴"},
  {"id":"65","name":"Ecuador","iso2":"EC","iso3":"ECU","code":"593","flag":"🇪🇨"},
  {"id":"66","name":"Egypt","iso2":"EG","iso3":"EGY","code":"20","flag":"🇪🇬"},
  {"id":"67","name":"El Salvador","iso2":"SV","iso3":"SLV","code":"503","flag":"🇸🇻"},
  {"id":"68","name":"England","iso2":"GB","iso3":"GBR","code":"44","flag":"🏴󠁧󠁢󠁥󠁮󠁧󠁿"},
  {"id":"69","name":"Equatorial Guinea","iso2":"GQ","iso3":"GNQ","code":"240","flag":"🇬🇶"},
  {"id":"70","name":"Eritrea","iso2":"ER","iso3":"ERI","code":"291","flag":"🇪🇷"},
  {"id":"71","name":"Estonia","iso2":"EE","iso3":"EST","code":"372","flag":"🇪🇪"},
  {"id":"72","name":"Eswatini (Swaziland)","iso2":"SZ","iso3":"SWZ","code":"268","flag":"🇸🇿"},
  {"id":"73","name":"Ethiopia","iso2":"ET","iso3":"ETH","code":"251","flag":"🇪🇹"},
  {"id":"74","name":"Falkland Islands","iso2":"FK","iso3":"FLK","code":"500","flag":"🇫🇰"},
  {"id":"75","name":"Faroe Islands","iso2":"FO","iso3":"FRO","code":"298","flag":"🇫🇴"},
  {"id":"76","name":"Fiji","iso2":"FJ","iso3":"FJI","code":"679","flag":"🇫🇯"},
  {"id":"77","name":"Finland","iso2":"FI","iso3":"FIN","code":"358","flag":"🇫🇮"},
  {"id":"78","name":"France","iso2":"FR","iso3":"FRA","code":"33","flag":"🇫🇷"},
  {"id":"79","name":"French Guiana","iso2":"GF","iso3":"GUF","code":"594","flag":"🇬🇫"},
  {"id":"80","name":"French Polynesia","iso2":"PF","iso3":"PYF","code":"689","flag":"🇵🇫"},
  {"id":"81","name":"French Southern and Antarctic Lands","iso2":"TF","iso3":"ATF","code":"N\/A","flag":"🇹🇫"},
  {"id":"82","name":"Gabon","iso2":"GA","iso3":"GAB","code":"241","flag":"🇬🇦"},
  {"id":"83","name":"Gambia","iso2":"GM","iso3":"GMB","code":"220","flag":"🇬🇲"},
  {"id":"84","name":"Georgia","iso2":"GE","iso3":"GEO","code":"995","flag":"🇬🇪"},
  {"id":"85","name":"Germany","iso2":"DE","iso3":"DEU","code":"49","flag":"🇩🇪"},
  {"id":"86","name":"Ghana","iso2":"GH","iso3":"GHA","code":"233","flag":"🇬🇭"},
  {"id":"87","name":"Gibraltar","iso2":"GI","iso3":"GIB","code":"350","flag":"🇬🇮"},
  {"id":"88","name":"Greece","iso2":"GR","iso3":"GRC","code":"30","flag":"🇬🇷"},
  {"id":"89","name":"Greenland","iso2":"GL","iso3":"GRL","code":"299","flag":"🇬🇱"},
  {"id":"90","name":"Grenada","iso2":"GD","iso3":"GRD","code":"1","flag":"🇬🇩"},
  {"id":"91","name":"Guadeloupe","iso2":"GP","iso3":"GLP","code":"590","flag":"🇬🇵"},
  {"id":"92","name":"Guam","iso2":"GU","iso3":"GUM","code":"1","flag":"🇬🇺"},
  {"id":"93","name":"Guatemala","iso2":"GT","iso3":"GTM","code":"502","flag":"🇬🇹"},
  {"id":"94","name":"Guernsey","iso2":"GG","iso3":"GGY","code":"44","flag":"🇬🇬"},
  {"id":"95","name":"Guinea","iso2":"GN","iso3":"GIN","code":"224","flag":"🇬🇳"},
  {"id":"96","name":"Guinea-Bissau","iso2":"GW","iso3":"GNB","code":"245","flag":"🇬🇼"},
  {"id":"97","name":"Guyana","iso2":"GY","iso3":"GUY","code":"592","flag":"🇬🇾"},
  {"id":"98","name":"Haiti","iso2":"HT","iso3":"HTI","code":"509","flag":"🇭🇹"},
  {"id":"99","name":"Heard Island and McDonald Island","iso2":"HM","iso3":"HMD","code":"N\/A","flag":"🇭🇲"},
  {"id":"100","name":"Honduras","iso2":"HN","iso3":"HND","code":"504","flag":"🇭🇳"},
  {"id":"101","name":"Hong Kong","iso2":"HK","iso3":"HKG","code":"852","flag":"🇭🇰"},
  {"id":"102","name":"Hungary","iso2":"HU","iso3":"HUN","code":"36","flag":"🇭🇺"},
  {"id":"103","name":"Iceland","iso2":"IS","iso3":"ISL","code":"354","flag":"🇮🇸"},
  {"id":"104","name":"India","iso2":"IN","iso3":"IND","code":"91","flag":"🇮🇳"},
  {"id":"105","name":"Indonesia","iso2":"ID","iso3":"IDN","code":"62","flag":"🇮🇩"},
  {"id":"106","name":"Iran","iso2":"IR","iso3":"IRN","code":"98","flag":"🇮🇷"},
  {"id":"107","name":"Iraq","iso2":"IQ","iso3":"IRQ","code":"964","flag":"🇮🇶"},
  {"id":"108","name":"Ireland","iso2":"IE","iso3":"IRL","code":"353","flag":"🇮🇪"},
  {"id":"109","name":"Isle of Man","iso2":"IM","iso3":"IMN","code":"44","flag":"🇮🇲"},
  {"id":"110","name":"Israel","iso2":"IL","iso3":"ISR","code":"972","flag":"🇮🇱"},
  {"id":"111","name":"Italy","iso2":"IT","iso3":"ITA","code":"39","flag":"🇮🇹"},
  {"id":"112","name":"Jamaica","iso2":"JM","iso3":"JAM","code":"1","flag":"🇯🇲"},
  {"id":"113","name":"Japan","iso2":"JP","iso3":"JPN","code":"81","flag":"🇯🇵"},
  {"id":"114","name":"Jersey","iso2":"JE","iso3":"JEY","code":"44","flag":"🇯🇪"},
  {"id":"115","name":"Jordan","iso2":"JO","iso3":"JOR","code":"962","flag":"🇯🇴"},
  {"id":"116","name":"Kazakhstan","iso2":"KZ","iso3":"KAZ","code":"7","flag":"🇰🇿"},
  {"id":"117","name":"Kenya","iso2":"KE","iso3":"KEN","code":"254","flag":"🇰🇪"},
  {"id":"118","name":"Kiribati","iso2":"KI","iso3":"KIR","code":"686","flag":"🇰🇮"},
  {"id":"119","name":"North Korea","iso2":"KP","iso3":"PRK","code":"850","flag":"🇰🇵"},
  {"id":"120","name":"South Korea","iso2":"KR","iso3":"KOR","code":"82","flag":"🇰🇷"},
  {"id":"121","name":"Kosovo","iso2":"XK","iso3":"XKX","code":"383","flag":"🇽🇰"},
  {"id":"122","name":"Kuwait","iso2":"KW","iso3":"KWT","code":"965","flag":"🇰🇼"},
  {"id":"123","name":"Kyrgyzstan","iso2":"KG","iso3":"KGZ","code":"996","flag":"🇰🇬"},
  {"id":"124","name":"Laos","iso2":"LA","iso3":"LAO","code":"856","flag":"🇱🇦"},
  {"id":"125","name":"Latvia","iso2":"LV","iso3":"LVA","code":"371","flag":"🇱🇻"},
  {"id":"126","name":"Lebanon","iso2":"LB","iso3":"LBN","code":"961","flag":"🇱🇧"},
  {"id":"127","name":"Lesotho","iso2":"LS","iso3":"LSO","code":"266","flag":"🇱🇸"},
  {"id":"128","name":"Liberia","iso2":"LR","iso3":"LBR","code":"231","flag":"🇱🇷"},
  {"id":"129","name":"Libya","iso2":"LY","iso3":"LBY","code":"218","flag":"🇱🇾"},
  {"id":"130","name":"Liechtenstein","iso2":"LI","iso3":"LIE","code":"423","flag":"🇱🇮"},
  {"id":"131","name":"Lithuania","iso2":"LT","iso3":"LTU","code":"370","flag":"🇱🇹"},
  {"id":"132","name":"Luxembourg","iso2":"LU","iso3":"LUX","code":"352","flag":"🇱🇺"},
  {"id":"133","name":"Macau","iso2":"MO","iso3":"MAC","code":"853","flag":"🇲🇴"},
  {"id":"134","name":"Madagascar","iso2":"MG","iso3":"MDG","code":"261","flag":"🇲🇬"},
  {"id":"135","name":"Malawi","iso2":"MW","iso3":"MWI","code":"265","flag":"🇲🇼"},
  {"id":"136","name":"Malaysia","iso2":"MY","iso3":"MYS","code":"60","flag":"🇲🇾"},
  {"id":"137","name":"Maldives","iso2":"MV","iso3":"MDV","code":"960","flag":"🇲🇻"},
  {"id":"138","name":"Mali","iso2":"ML","iso3":"MLI","code":"223","flag":"🇲🇱"},
  {"id":"139","name":"Malta","iso2":"MT","iso3":"MLT","code":"356","flag":"🇲🇹"},
  {"id":"140","name":"Marshall Islands","iso2":"MH","iso3":"MHL","code":"692","flag":"🇲🇭"},
  {"id":"141","name":"Martinique","iso2":"MQ","iso3":"MTQ","code":"596","flag":"🇲🇶"},
  {"id":"142","name":"Mauritania","iso2":"MR","iso3":"MRT","code":"222","flag":"🇲🇷"},
  {"id":"143","name":"Mauritius","iso2":"MU","iso3":"MUS","code":"230","flag":"🇲🇺"},
  {"id":"144","name":"Mayotte","iso2":"YT","iso3":"MYT","code":"262","flag":"🇾🇹"},
  {"id":"145","name":"Mexico","iso2":"MX","iso3":"MEX","code":"52","flag":"🇲🇽"},
  {"id":"146","name":"Micronesia","iso2":"FM","iso3":"FSM","code":"691","flag":"🇫🇲"},
  {"id":"147","name":"Moldova","iso2":"MD","iso3":"MDA","code":"373","flag":"🇲🇩"},
  {"id":"148","name":"Monaco","iso2":"MC","iso3":"MCO","code":"377","flag":"🇲🇨"},
  {"id":"149","name":"Mongolia","iso2":"MN","iso3":"MNG","code":"976","flag":"🇲🇳"},
  {"id":"150","name":"Montenegro","iso2":"ME","iso3":"MNE","code":"382","flag":"🇲🇪"},
  {"id":"151","name":"Montserrat","iso2":"MS","iso3":"MSR","code":"1","flag":"🇲🇸"},
  {"id":"152","name":"Morocco","iso2":"MA","iso3":"MAR","code":"212","flag":"🇲🇦"},
  {"id":"153","name":"Mozambique","iso2":"MZ","iso3":"MOZ","code":"258","flag":"🇲🇿"},
  {"id":"154","name":"Myanmar","iso2":"MM","iso3":"MMR","code":"95","flag":"🇲🇲"},
  {"id":"155","name":"Namibia","iso2":"NA","iso3":"NAM","code":"264","flag":"🇳🇦"},
  {"id":"156","name":"Nauru","iso2":"NR","iso3":"NRU","code":"674","flag":"🇳🇷"},
  {"id":"157","name":"Nepal","iso2":"NP","iso3":"NPL","code":"977","flag":"🇳🇵"},
  {"id":"158","name":"Netherlands","iso2":"NL","iso3":"NLD","code":"31","flag":"🇳🇱"},
  {"id":"159","name":"New Caledonia","iso2":"NC","iso3":"NCL","code":"687","flag":"🇳🇨"},
  {"id":"160","name":"New Zealand","iso2":"NZ","iso3":"NZL","code":"64","flag":"🇳🇿"},
  {"id":"161","name":"Nicaragua","iso2":"NI","iso3":"NIC","code":"505","flag":"🇳🇮"},
  {"id":"162","name":"Niger","iso2":"NE","iso3":"NER","code":"227","flag":"🇳🇪"},
  {"id":"163","name":"Nigeria","iso2":"NG","iso3":"NGA","code":"234","flag":"🇳🇬"},
  {"id":"164","name":"Niue","iso2":"NU","iso3":"NIU","code":"683","flag":"🇳🇺"},
  {"id":"165","name":"Norfolk Island","iso2":"NF","iso3":"NFK","code":"672","flag":"🇳🇫"},
  {"id":"166","name":"North Macedonia","iso2":"MK","iso3":"MKD","code":"389","flag":"🇲🇰"},
  {"id":"167","name":"Northern Mariana Islands","iso2":"MP","iso3":"MNP","code":"1","flag":"🇲🇵"},
  {"id":"168","name":"Norway","iso2":"NO","iso3":"NOR","code":"47","flag":"🇳🇴"},
  {"id":"169","name":"Oman","iso2":"OM","iso3":"OMN","code":"968","flag":"🇴🇲"},
  {"id":"170","name":"Pakistan","iso2":"PK","iso3":"PAK","code":"92","flag":"🇵🇰"},
  {"id":"171","name":"Palau","iso2":"PW","iso3":"PLW","code":"680","flag":"🇵🇼"},
  {"id":"172","name":"Palestine","iso2":"PS","iso3":"PSE","code":"970","flag":"🇵🇸"},
  {"id":"173","name":"Panama","iso2":"PA","iso3":"PAN","code":"507","flag":"🇵🇦"},
  {"id":"174","name":"Papua New Guinea","iso2":"PG","iso3":"PNG","code":"675","flag":"🇵🇬"},
  {"id":"175","name":"Paraguay","iso2":"PY","iso3":"PRY","code":"595","flag":"🇵🇾"},
  {"id":"176","name":"Peru","iso2":"PE","iso3":"PER","code":"51","flag":"🇵🇪"},
  {"id":"177","name":"Philippines","iso2":"PH","iso3":"PHL","code":"63","flag":"🇵🇭"},
  {"id":"178","name":"Pitcairn Islands","iso2":"PN","iso3":"PCN","code":"64","flag":"🇵🇳"},
  {"id":"179","name":"Poland","iso2":"PL","iso3":"POL","code":"48","flag":"🇵🇱"},
  {"id":"180","name":"Portugal","iso2":"PT","iso3":"PRT","code":"351","flag":"🇵🇹"},
  {"id":"181","name":"Puerto Rico","iso2":"PR","iso3":"PRI","code":"1","flag":"🇵🇷"},
  {"id":"182","name":"Qatar","iso2":"QA","iso3":"QAT","code":"974","flag":"🇶🇦"},
  {"id":"183","name":"Réunion","iso2":"RE","iso3":"REU","code":"262","flag":"🇷🇪"},
  {"id":"184","name":"Romania","iso2":"RO","iso3":"ROU","code":"40","flag":"🇷🇴"},
  {"id":"185","name":"Russia","iso2":"RU","iso3":"RUS","code":"7","flag":"🇷🇺"},
  {"id":"186","name":"Rwanda","iso2":"RW","iso3":"RWA","code":"250","flag":"🇷🇼"},
  {"id":"187","name":"Saint Barthélemy","iso2":"BL","iso3":"BLM","code":"590","flag":"🇧🇱"},
  {"id":"188","name":"Saint Helena, Ascension and Tristan da Cunha","iso2":"SH","iso3":"SHN","code":"290","flag":"🇸🇭"},
  {"id":"189","name":"Saint Kitts and Nevis","iso2":"KN","iso3":"KNA","code":"1","flag":"🇰🇳"},
  {"id":"190","name":"Saint Lucia","iso2":"LC","iso3":"LCA","code":"1","flag":"🇱🇨"},
  {"id":"191","name":"Saint Martin","iso2":"MF","iso3":"MAF","code":"590","flag":"🇲🇫"},
  {"id":"192","name":"Saint Pierre and Miquelon","iso2":"PM","iso3":"SPM","code":"508","flag":"🇵🇲"},
  {"id":"193","name":"Saint Vincent and the Grenadines","iso2":"VC","iso3":"VCT","code":"1","flag":"🇻🇨"},
  {"id":"194","name":"Samoa","iso2":"WS","iso3":"WSM","code":"685","flag":"🇼🇸"},
  {"id":"195","name":"San Marino","iso2":"SM","iso3":"SMR","code":"378","flag":"🇸🇲"},
  {"id":"196","name":"São Tomé and Príncipe","iso2":"ST","iso3":"STP","code":"239","flag":"🇸🇹"},
  {"id":"197","name":"Saudi Arabia","iso2":"SA","iso3":"SAU","code":"966","flag":"🇸🇦"},
  {"id":"198","name":"Scotland","iso2":"GB-SCT","iso3":"SCT","code":"44","flag":"🏴󠁧󠁢󠁳󠁣󠁴󠁿"},
  {"id":"199","name":"Senegal","iso2":"SN","iso3":"SEN","code":"221","flag":"🇸🇳"},
  {"id":"200","name":"Serbia","iso2":"RS","iso3":"SRB","code":"381","flag":"🇷🇸"},
  {"id":"201","name":"Seychelles","iso2":"SC","iso3":"SYC","code":"248","flag":"🇸🇨"},
  {"id":"202","name":"Sierra Leone","iso2":"SL","iso3":"SLE","code":"232","flag":"🇸🇱"},
  {"id":"203","name":"Singapore","iso2":"SG","iso3":"SGP","code":"65","flag":"🇸🇬"},
  {"id":"204","name":"Sint Maarten","iso2":"SX","iso3":"SXM","code":"1","flag":"🇸🇽"},
  {"id":"205","name":"Slovakia","iso2":"SK","iso3":"SVK","code":"421","flag":"🇸🇰"},
  {"id":"206","name":"Slovenia","iso2":"SI","iso3":"SVN","code":"386","flag":"🇸🇮"},
  {"id":"207","name":"Solomon Islands","iso2":"SB","iso3":"SLB","code":"677","flag":"🇸🇧"},
  {"id":"208","name":"Somalia","iso2":"SO","iso3":"SOM","code":"252","flag":"🇸🇴"},
  {"id":"209","name":"South Africa","iso2":"ZA","iso3":"ZAF","code":"27","flag":"🇿🇦"},
  {"id":"210","name":"South Georgia","iso2":"GS","iso3":"SGS","code":"N\/A","flag":"🇬🇸"},
  {"id":"211","name":"South Sudan","iso2":"SS","iso3":"SSD","code":"211","flag":"🇸🇸"},
  {"id":"212","name":"Spain","iso2":"ES","iso3":"ESP","code":"34","flag":"🇪🇸"},
  {"id":"213","name":"Sri Lanka","iso2":"LK","iso3":"LKA","code":"94","flag":"🇱🇰"},
  {"id":"214","name":"Sudan","iso2":"SD","iso3":"SDN","code":"249","flag":"🇸🇩"},
  {"id":"215","name":"Suriname","iso2":"SR","iso3":"SUR","code":"597","flag":"🇸🇷"},
  {"id":"216","name":"Svalbard and Jan Mayen","iso2":"SJ","iso3":"SJM","code":"47","flag":"🇸🇯"},
  {"id":"217","name":"Sweden","iso2":"SE","iso3":"SWE","code":"46","flag":"🇸🇪"},
  {"id":"218","name":"Switzerland","iso2":"CH","iso3":"CHE","code":"41","flag":"🇨🇭"},
  {"id":"219","name":"Syria","iso2":"SY","iso3":"SYR","code":"963","flag":"🇸🇾"},
  {"id":"220","name":"Taiwan","iso2":"TW","iso3":"TWN","code":"886","flag":"🇹🇼"},
  {"id":"221","name":"Tajikistan","iso2":"TJ","iso3":"TJK","code":"992","flag":"🇹🇯"},
  {"id":"222","name":"Tanzania","iso2":"TZ","iso3":"TZA","code":"255","flag":"🇹🇿"},
  {"id":"223","name":"Thailand","iso2":"TH","iso3":"THA","code":"66","flag":"🇹🇭"},
  {"id":"224","name":"Timor-Leste","iso2":"TL","iso3":"TLS","code":"670","flag":"🇹🇱"},
  {"id":"225","name":"Togo","iso2":"TG","iso3":"TGO","code":"228","flag":"🇹🇬"},
  {"id":"226","name":"Tokelau","iso2":"TK","iso3":"TKL","code":"690","flag":"🇹🇰"},
  {"id":"227","name":"Tonga","iso2":"TO","iso3":"TON","code":"676","flag":"🇹🇴"},
  {"id":"228","name":"Trinidad and Tobago","iso2":"TT","iso3":"TTO","code":"1","flag":"🇹🇹"},
  {"id":"229","name":"Tunisia","iso2":"TN","iso3":"TUN","code":"216","flag":"🇹🇳"},
  {"id":"230","name":"Turkey","iso2":"TR","iso3":"TUR","code":"90","flag":"🇹🇷"},
  {"id":"231","name":"Turkmenistan","iso2":"TM","iso3":"TKM","code":"993","flag":"🇹🇲"},
  {"id":"232","name":"Turks and Caicos Islands","iso2":"TC","iso3":"TCA","code":"1","flag":"🇹🇨"},
  {"id":"233","name":"Tuvalu","iso2":"TV","iso3":"TUV","code":"688","flag":"🇹🇻"},
  {"id":"234","name":"Uganda","iso2":"UG","iso3":"UGA","code":"256","flag":"🇺🇬"},
  {"id":"235","name":"Ukraine","iso2":"UA","iso3":"UKR","code":"380","flag":"🇺🇦"},
  {"id":"236","name":"United Arab Emirates","iso2":"AE","iso3":"ARE","code":"971","flag":"🇦🇪"},
  {"id":"237","name":"United Kingdom","iso2":"GB","iso3":"GBR","code":"44","flag":"🇬🇧"},
  {"id":"238","name":"United States","iso2":"US","iso3":"USA","code":"1","flag":"🇺🇸"},
  {"id":"239","name":"United States Minor Outlying Islands","iso2":"UM","iso3":"USA","code":"1","flag":"🇺🇲"},
  {"id":"240","name":"Uruguay","iso2":"UY","iso3":"URY","code":"598","flag":"🇺🇾"},
  {"id":"241","name":"Uzbekistan","iso2":"UZ","iso3":"UZB","code":"998","flag":"🇺🇿"},
  {"id":"242","name":"Vanuatu","iso2":"VU","iso3":"VUT","code":"678","flag":"🇻🇺"},
  {"id":"243","name":"Vatican City (Holy See)","iso2":"VA","iso3":"VAT","code":"39","flag":"🇻🇦"},
  {"id":"244","name":"Venezuela","iso2":"VE","iso3":"VEN","code":"58","flag":"🇻🇪"},
  {"id":"245","name":"Vietnam","iso2":"VN","iso3":"VNM","code":"84","flag":"🇻🇳"},
  {"id":"246","name":"British Virgin Islands","iso2":"VG","iso3":"VGB","code":"1","flag":"🇻🇬"},
  {"id":"247","name":"United States Virgin Islands","iso2":"VI","iso3":"VIR","code":"1","flag":"🇻🇮"},
  {"id":"248","name":"Wales","iso2":"GB-WLS","iso3":"WLS","code":"44","flag":"🏴󠁧󠁢󠁷󠁬󠁳󠁿"},
  {"id":"249","name":"Wallis and Futuna","iso2":"WF","iso3":"WLF","code":"681","flag":"🇼🇫"},
  {"id":"250","name":"Western Sahara","iso2":"EH","iso3":"ESH","code":"212","flag":"🇪🇭"},
  {"id":"251","name":"Yemen","iso2":"YE","iso3":"YEM","code":"967","flag":"🇾🇪"},
  {"id":"252","name":"Zambia","iso2":"ZM","iso3":"ZMB","code":"260","flag":"🇿🇲"},
  {"id":"253","name":"Zimbabwe","iso2":"ZW","iso3":"ZWE","code":"263","flag":"🇿🇼"}
]