export const countries = [
  { "iso3" : "AF", "iso2" : "AF", "code" : "+93", "flag" : "🇦🇫", "name" : "Afghanistan"},
  { "iso3" : "ALA", "iso2" : "AX", "code" : "+358", "flag" : "🇦🇽", "name" : "Åland Islands"},
  { "iso3" : "AL", "iso2" : "AL", "code" : "+355", "flag" : "🇦🇱", "name" : "Albania"},
  { "iso3" : "DZA", "iso2" : "DZ", "code" : "+213", "flag" : "🇩🇿", "name" : "Algeria"},
  { "iso3" : "ASM", "iso2" : "AS", "code" : "+1", "flag" : "🇦🇸", "name" : "American Samoa"},
  { "iso3" : "AND", "iso2" : "AD", "code" : "+376", "flag" : "🇦🇩", "name" : "Andorra"},
  { "iso3" : "AGO", "iso2" : "AO", "code" : "+244", "flag" : "🇦🇴", "name" : "Angola"},
  { "iso3" : "AIA", "iso2" : "AI", "code" : "+1", "flag" : "🇦🇮", "name" : "Anguilla"},
  { "iso3" : "ATA", "iso2" : "AQ", "code" : "+672", "flag" : "🇦🇶", "name" : "Antarctica"},
  { "iso3" : "ATG", "iso2" : "AG", "code" : "+1", "flag" : "🇦🇬", "name" : "Antigua and Barbuda"},
  { "iso3" : "ARG", "iso2" : "AR", "code" : "+54", "flag" : "🇦🇷", "name" : "Argentina"},
  { "iso3" : "ARM", "iso2" : "AM", "code" : "+374", "flag" : "🇦🇲", "name" : "Armenia"},
  { "iso3" : "ABW", "iso2" : "AW", "code" : "+297", "flag" : "🇦🇼", "name" : "Aruba"},
  { "iso3" : "AUS", "iso2" : "AU", "code" : "+61", "flag" : "🇦🇺", "name" : "Australia"},
  { "iso3" : "AUT", "iso2" : "AT", "code" : "+43", "flag" : "🇦🇹", "name" : "Austria"},
  { "iso3" : "AZE", "iso2" : "AZ", "code" : "+994", "flag" : "🇦🇿", "name" : "Azerbaijan"},
  { "iso3" : "BHS", "iso2" : "BS", "code" : "+1", "flag" : "🇧🇸", "name" : "Bahamas"},
  { "iso3" : "BHR", "iso2" : "BH", "code" : "+973", "flag" : "🇧🇭", "name" : "Bahrain"},
  { "iso3" : "BGD", "iso2" : "BD", "code" : "+880", "flag" : "🇧🇩", "name" : "Bangladesh"},
  { "iso3" : "BRB", "iso2" : "BB", "code" : "+1", "flag" : "🇧🇧", "name" : "Barbados"},
  { "iso3" : "BLR", "iso2" : "BY", "code" : "+375", "flag" : "🇧🇾", "name" : "Belarus"},
  { "iso3" : "BEL", "iso2" : "BE", "code" : "+32", "flag" : "🇧🇪", "name" : "Belgium"},
  { "iso3" : "BLZ", "iso2" : "BZ", "code" : "+501", "flag" : "🇧🇿", "name" : "Belize"},
  { "iso3" : "BEN", "iso2" : "BJ", "code" : "+229", "flag" : "🇧🇯", "name" : "Benin"},
  { "iso3" : "BMU", "iso2" : "BM", "code" : "+1", "flag" : "🇧🇲", "name" : "Bermuda"},
  { "iso3" : "BTN", "iso2" : "BT", "code" : "+975", "flag" : "🇧🇹", "name" : "Bhutan"},
  { "iso3" : "BOL", "iso2" : "BO", "code" : "+591", "flag" : "🇧🇴", "name" : "Bolivia"},
  { "iso3" : "BIH", "iso2" : "BA", "code" : "+387", "flag" : "🇧🇦", "name" : "Bosnia and Herzegovina"},
  { "iso3" : "BWA", "iso2" : "BW", "code" : "+267", "flag" : "🇧🇼", "name" : "Botswana"},
  { "iso3" : "BVT", "iso2" : "BV", "code" : "N/A", "flag" : "🇧🇻", "name" : "Bouvet Island"},
  { "iso3" : "BRA", "iso2" : "BR", "code" : "+55", "flag" : "🇧🇷", "name" : "Brazil"},
  { "iso3" : "IOT", "iso2" : "IO", "code" : "+246", "flag" : "🇮🇴", "name" : "British Indian Ocean Territory"},
  { "iso3" : "BRN", "iso2" : "BN", "code" : "+673", "flag" : "🇧🇳", "name" : "Brunei"},
  { "iso3" : "BGR", "iso2" : "BG", "code" : "+359", "flag" : "🇧🇬", "name" : "Bulgaria"},
  { "iso3" : "BFA", "iso2" : "BF", "code" : "+226", "flag" : "🇧🇫", "name" : "Burkina Faso"},
  { "iso3" : "BDI", "iso2" : "BI", "code" : "+257", "flag" : "🇧🇮", "name" : "Burundi"},
  { "iso3" : "KHM", "iso2" : "KH", "code" : "+855", "flag" : "🇰🇭", "name" : "Cambodia"},
  { "iso3" : "CMR", "iso2" : "CM", "code" : "+237", "flag" : "🇨🇲", "name" : "Cameroon"},
  { "iso3" : "CAN", "iso2" : "CA", "code" : "+1", "flag" : "🇨🇦", "name" : "Canada"},
  { "iso3" : "CPV", "iso2" : "CV", "code" : "+238", "flag" : "🇨🇻", "name" : "Cape Verde"},
  { "iso3" : "BES", "iso2" : "BQ", "code" : "+599", "flag" : "🇧🇶", "name" : "Caribbean Netherlands"},
  { "iso3" : "CYM", "iso2" : "KY", "code" : "+1", "flag" : "🇰🇾", "name" : "Cayman Islands"},
  { "iso3" : "CAF", "iso2" : "CF", "code" : "+236", "flag" : "🇨🇫", "name" : "Central African Republic"},
  { "iso3" : "TCD", "iso2" : "TD", "code" : "+235", "flag" : "🇹🇩", "name" : "Chad"},
  { "iso3" : "CHL", "iso2" : "CL", "code" : "+56", "flag" : "🇨🇱", "name" : "Chile"},
  { "iso3" : "CHN", "iso2" : "CN", "code" : "+86", "flag" : "🇨🇳", "name" : "China"},
  { "iso3" : "CXR", "iso2" : "CX", "code" : "+61", "flag" : "🇨🇽", "name" : "Christmas Island"},
  { "iso3" : "CCK", "iso2" : "CC", "code" : "+61", "flag" : "🇨🇨", "name" : "Cocos (Keeling) Islands"},
  { "iso3" : "COL", "iso2" : "CO", "code" : "+57", "flag" : "🇨🇴", "name" : "Colombia"},
  { "iso3" : "COM", "iso2" : "KM", "code" : "+269", "flag" : "🇰🇲", "name" : "Comoros"},
  { "iso3" : "COG", "iso2" : "CG", "code" : "+242", "flag" : "🇨🇬", "name" : "Republic of the Congo"},
  { "iso3" : "COD", "iso2" : "CD", "code" : "+243", "flag" : "🇨🇩", "name" : "DR Congo"},
  { "iso3" : "COK", "iso2" : "CK", "code" : "+682", "flag" : "🇨🇰", "name" : "Cook Islands"},
  { "iso3" : "CRI", "iso2" : "CR", "code" : "+506", "flag" : "🇨🇷", "name" : "Costa Rica"},
  { "iso3" : "CIV", "iso2" : "CI", "code" : "+225", "flag" : "🇨🇮", "name" : "Côte d'Ivoire (Ivory Coast)"},
  { "iso3" : "HRV", "iso2" : "HR", "code" : "+385", "flag" : "🇭🇷", "name" : "Croatia"},
  { "iso3" : "CUB", "iso2" : "CU", "code" : "+53", "flag" : "🇨🇺", "name" : "Cuba"},
  { "iso3" : "CUW", "iso2" : "CW", "code" : "+599", "flag" : "🇨🇼", "name" : "Curaçao"},
  { "iso3" : "CYP", "iso2" : "CY", "code" : "+357", "flag" : "🇨🇾", "name" : "Cyprus"},
  { "iso3" : "CZE", "iso2" : "CZ", "code" : "+420", "flag" : "🇨🇿", "name" : "Czechia"},
  { "iso3" : "DNK", "iso2" : "DK", "code" : "+45", "flag" : "🇩🇰", "name" : "Denmark"},
  { "iso3" : "DJI", "iso2" : "DJ", "code" : "+253", "flag" : "🇩🇯", "name" : "Djibouti"},
  { "iso3" : "DMA", "iso2" : "DM", "code" : "+1", "flag" : "🇩🇲", "name" : "Dominica"},
  { "iso3" : "DOM", "iso2" : "DO", "code" : "+1", "flag" : "🇩🇴", "name" : "Dominican Republic"},
  { "iso3" : "ECU", "iso2" : "EC", "code" : "+593", "flag" : "🇪🇨", "name" : "Ecuador"},
  { "iso3" : "EGY", "iso2" : "EG", "code" : "+20", "flag" : "🇪🇬", "name" : "Egypt"},
  { "iso3" : "SLV", "iso2" : "SV", "code" : "+503", "flag" : "🇸🇻", "name" : "El Salvador"},
  { "iso3" : "GBR", "iso2" : "GB", "code" : "+44", "flag" : "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "name" : "England"},
  { "iso3" : "GNQ", "iso2" : "GQ", "code" : "+240", "flag" : "🇬🇶", "name" : "Equatorial Guinea"},
  { "iso3" : "ERI", "iso2" : "ER", "code" : "+291", "flag" : "🇪🇷", "name" : "Eritrea"},
  { "iso3" : "EST", "iso2" : "EE", "code" : "+372", "flag" : "🇪🇪", "name" : "Estonia"},
  { "iso3" : "SWZ", "iso2" : "SZ", "code" : "+268", "flag" : "🇸🇿", "name" : "Eswatini (Swaziland)"},
  { "iso3" : "ETH", "iso2" : "ET", "code" : "+251", "flag" : "🇪🇹", "name" : "Ethiopia"},
  { "iso3" : "FLK", "iso2" : "FK", "code" : "+500", "flag" : "🇫🇰", "name" : "Falkland Islands"},
  { "iso3" : "FRO", "iso2" : "FO", "code" : "+298", "flag" : "🇫🇴", "name" : "Faroe Islands"},
  { "iso3" : "FJI", "iso2" : "FJ", "code" : "+679", "flag" : "🇫🇯", "name" : "Fiji"},
  { "iso3" : "FIN", "iso2" : "FI", "code" : "+358", "flag" : "🇫🇮", "name" : "Finland"},
  { "iso3" : "FRA", "iso2" : "FR", "code" : "+33", "flag" : "🇫🇷", "name" : "France"},
  { "iso3" : "GUF", "iso2" : "GF", "code" : "+594", "flag" : "🇬🇫", "name" : "French Guiana"},
  { "iso3" : "PYF", "iso2" : "PF", "code" : "+689", "flag" : "🇵🇫", "name" : "French Polynesia"},
  { "iso3" : "ATF", "iso2" : "TF", "code" : "N/A", "flag" : "🇹🇫", "name" : "French Southern and Antarctic Lands"},
  { "iso3" : "GAB", "iso2" : "GA", "code" : "+241", "flag" : "🇬🇦", "name" : "Gabon"},
  { "iso3" : "GMB", "iso2" : "GM", "code" : "+220", "flag" : "🇬🇲", "name" : "Gambia"},
  { "iso3" : "GEO", "iso2" : "GE", "code" : "+995", "flag" : "🇬🇪", "name" : "Georgia"},
  { "iso3" : "DEU", "iso2" : "DE", "code" : "+49", "flag" : "🇩🇪", "name" : "Germany"},
  { "iso3" : "GHA", "iso2" : "GH", "code" : "+233", "flag" : "🇬🇭", "name" : "Ghana"},
  { "iso3" : "GIB", "iso2" : "GI", "code" : "+350", "flag" : "🇬🇮", "name" : "Gibraltar"},
  { "iso3" : "GRC", "iso2" : "GR", "code" : "+30", "flag" : "🇬🇷", "name" : "Greece"},
  { "iso3" : "GRL", "iso2" : "GL", "code" : "+299", "flag" : "🇬🇱", "name" : "Greenland"},
  { "iso3" : "GRD", "iso2" : "GD", "code" : "+1", "flag" : "🇬🇩", "name" : "Grenada"},
  { "iso3" : "GLP", "iso2" : "GP", "code" : "+590", "flag" : "🇬🇵", "name" : "Guadeloupe"},
  { "iso3" : "GUM", "iso2" : "GU", "code" : "+1", "flag" : "🇬🇺", "name" : "Guam"},
  { "iso3" : "GTM", "iso2" : "GT", "code" : "+502", "flag" : "🇬🇹", "name" : "Guatemala"},
  { "iso3" : "GGY", "iso2" : "GG", "code" : "+44", "flag" : "🇬🇬", "name" : "Guernsey"},
  { "iso3" : "GIN", "iso2" : "GN", "code" : "+224", "flag" : "🇬🇳", "name" : "Guinea"},
  { "iso3" : "GNB", "iso2" : "GW", "code" : "+245", "flag" : "🇬🇼", "name" : "Guinea-Bissau"},
  { "iso3" : "GUY", "iso2" : "GY", "code" : "+592", "flag" : "🇬🇾", "name" : "Guyana"},
  { "iso3" : "HTI", "iso2" : "HT", "code" : "+509", "flag" : "🇭🇹", "name" : "Haiti"},
  { "iso3" : "HMD", "iso2" : "HM", "code" : "N/A", "flag" : "🇭🇲", "name" : "Heard Island and McDonald Island"},
  { "iso3" : "HND", "iso2" : "HN", "code" : "+504", "flag" : "🇭🇳", "name" : "Honduras"},
  { "iso3" : "HKG", "iso2" : "HK", "code" : "+852", "flag" : "🇭🇰", "name" : "Hong Kong"},
  { "iso3" : "HUN", "iso2" : "HU", "code" : "+36", "flag" : "🇭🇺", "name" : "Hungary"},
  { "iso3" : "ISL", "iso2" : "IS", "code" : "+354", "flag" : "🇮🇸", "name" : "Iceland"},
  { "iso3" : "IND", "iso2" : "IN", "code" : "+91", "flag" : "🇮🇳", "name" : "India"},
  { "iso3" : "IDN", "iso2" : "ID", "code" : "+62", "flag" : "🇮🇩", "name" : "Indonesia"},
  { "iso3" : "IRN", "iso2" : "IR", "code" : "+98", "flag" : "🇮🇷", "name" : "Iran"},
  { "iso3" : "IRQ", "iso2" : "IQ", "code" : "+964", "flag" : "🇮🇶", "name" : "Iraq"},
  { "iso3" : "IRL", "iso2" : "IE", "code" : "+353", "flag" : "🇮🇪", "name" : "Ireland"},
  { "iso3" : "IMN", "iso2" : "IM", "code" : "+44", "flag" : "🇮🇲", "name" : "Isle of Man"},
  // { "iso3" : "ISR", "iso2" : "IL", "code" : "+972", "flag" : "🇮🇱", "name" : "Israel"},
  { "iso3" : "ITA", "iso2" : "IT", "code" : "+39", "flag" : "🇮🇹", "name" : "Italy"},
  { "iso3" : "JAM", "iso2" : "JM", "code" : "+1", "flag" : "🇯🇲", "name" : "Jamaica"},
  { "iso3" : "JPN", "iso2" : "JP", "code" : "+81", "flag" : "🇯🇵", "name" : "Japan"},
  { "iso3" : "JEY", "iso2" : "JE", "code" : "+44", "flag" : "🇯🇪", "name" : "Jersey"},
  { "iso3" : "JOR", "iso2" : "JO", "code" : "+962", "flag" : "🇯🇴", "name" : "Jordan"},
  { "iso3" : "KAZ", "iso2" : "KZ", "code" : "+7", "flag" : "🇰🇿", "name" : "Kazakhstan"},
  { "iso3" : "KEN", "iso2" : "KE", "code" : "+254", "flag" : "🇰🇪", "name" : "Kenya"},
  { "iso3" : "KIR", "iso2" : "KI", "code" : "+686", "flag" : "🇰🇮", "name" : "Kiribati"},
  { "iso3" : "PRK", "iso2" : "KP", "code" : "+850", "flag" : "🇰🇵", "name" : "North Korea"},
  { "iso3" : "KOR", "iso2" : "KR", "code" : "+82", "flag" : "🇰🇷", "name" : "South Korea"},
  { "iso3" : "XKX", "iso2" : "XK", "code" : "+383", "flag" : "🇽🇰", "name" : "Kosovo"},
  { "iso3" : "KWT", "iso2" : "KW", "code" : "+965", "flag" : "🇰🇼", "name" : "Kuwait"},
  { "iso3" : "KGZ", "iso2" : "KG", "code" : "+996", "flag" : "🇰🇬", "name" : "Kyrgyzstan"},
  { "iso3" : "LAO", "iso2" : "LA", "code" : "+856", "flag" : "🇱🇦", "name" : "Laos"},
  { "iso3" : "LVA", "iso2" : "LV", "code" : "+371", "flag" : "🇱🇻", "name" : "Latvia"},
  { "iso3" : "LBN", "iso2" : "LB", "code" : "+961", "flag" : "🇱🇧", "name" : "Lebanon"},
  { "iso3" : "LSO", "iso2" : "LS", "code" : "+266", "flag" : "🇱🇸", "name" : "Lesotho"},
  { "iso3" : "LBR", "iso2" : "LR", "code" : "+231", "flag" : "🇱🇷", "name" : "Liberia"},
  { "iso3" : "LBY", "iso2" : "LY", "code" : "+218", "flag" : "🇱🇾", "name" : "Libya"},
  { "iso3" : "LIE", "iso2" : "LI", "code" : "+423", "flag" : "🇱🇮", "name" : "Liechtenstein"},
  { "iso3" : "LTU", "iso2" : "LT", "code" : "+370", "flag" : "🇱🇹", "name" : "Lithuania"},
  { "iso3" : "LUX", "iso2" : "LU", "code" : "+352", "flag" : "🇱🇺", "name" : "Luxembourg"},
  { "iso3" : "MAC", "iso2" : "MO", "code" : "+853", "flag" : "🇲🇴", "name" : "Macau"},
  { "iso3" : "MDG", "iso2" : "MG", "code" : "+261", "flag" : "🇲🇬", "name" : "Madagascar"},
  { "iso3" : "MWI", "iso2" : "MW", "code" : "+265", "flag" : "🇲🇼", "name" : "Malawi"},
  { "iso3" : "MYS", "iso2" : "MY", "code" : "+60", "flag" : "🇲🇾", "name" : "Malaysia"},
  { "iso3" : "MDV", "iso2" : "MV", "code" : "+960", "flag" : "🇲🇻", "name" : "Maldives"},
  { "iso3" : "MLI", "iso2" : "ML", "code" : "+223", "flag" : "🇲🇱", "name" : "Mali"},
  { "iso3" : "MLT", "iso2" : "MT", "code" : "+356", "flag" : "🇲🇹", "name" : "Malta"},
  { "iso3" : "MHL", "iso2" : "MH", "code" : "+692", "flag" : "🇲🇭", "name" : "Marshall Islands"},
  { "iso3" : "MTQ", "iso2" : "MQ", "code" : "+596", "flag" : "🇲🇶", "name" : "Martinique"},
  { "iso3" : "MRT", "iso2" : "MR", "code" : "+222", "flag" : "🇲🇷", "name" : "Mauritania"},
  { "iso3" : "MUS", "iso2" : "MU", "code" : "+230", "flag" : "🇲🇺", "name" : "Mauritius"},
  { "iso3" : "MYT", "iso2" : "YT", "code" : "+262", "flag" : "🇾🇹", "name" : "Mayotte"},
  { "iso3" : "MEX", "iso2" : "MX", "code" : "+52", "flag" : "🇲🇽", "name" : "Mexico"},
  { "iso3" : "FSM", "iso2" : "FM", "code" : "+691", "flag" : "🇫🇲", "name" : "Micronesia"},
  { "iso3" : "MDA", "iso2" : "MD", "code" : "+373", "flag" : "🇲🇩", "name" : "Moldova"},
  { "iso3" : "MCO", "iso2" : "MC", "code" : "+377", "flag" : "🇲🇨", "name" : "Monaco"},
  { "iso3" : "MNG", "iso2" : "MN", "code" : "+976", "flag" : "🇲🇳", "name" : "Mongolia"},
  { "iso3" : "MNE", "iso2" : "ME", "code" : "+382", "flag" : "🇲🇪", "name" : "Montenegro"},
  { "iso3" : "MSR", "iso2" : "MS", "code" : "+1", "flag" : "🇲🇸", "name" : "Montserrat"},
  { "iso3" : "MAR", "iso2" : "MA", "code" : "+212", "flag" : "🇲🇦", "name" : "Morocco"},
  { "iso3" : "MOZ", "iso2" : "MZ", "code" : "+258", "flag" : "🇲🇿", "name" : "Mozambique"},
  { "iso3" : "MMR", "iso2" : "MM", "code" : "+95", "flag" : "🇲🇲", "name" : "Myanmar"},
  { "iso3" : "NAM", "iso2" : "NA", "code" : "+264", "flag" : "🇳🇦", "name" : "Namibia"},
  { "iso3" : "NRU", "iso2" : "NR", "code" : "+674", "flag" : "🇳🇷", "name" : "Nauru"},
  { "iso3" : "NPL", "iso2" : "NP", "code" : "+977", "flag" : "🇳🇵", "name" : "Nepal"},
  { "iso3" : "NLD", "iso2" : "NL", "code" : "+31", "flag" : "🇳🇱", "name" : "Netherlands"},
  { "iso3" : "NCL", "iso2" : "NC", "code" : "+687", "flag" : "🇳🇨", "name" : "New Caledonia"},
  { "iso3" : "NZL", "iso2" : "NZ", "code" : "+64", "flag" : "🇳🇿", "name" : "New Zealand"},
  { "iso3" : "NIC", "iso2" : "NI", "code" : "+505", "flag" : "🇳🇮", "name" : "Nicaragua"},
  { "iso3" : "NER", "iso2" : "NE", "code" : "+227", "flag" : "🇳🇪", "name" : "Niger"},
  { "iso3" : "NGA", "iso2" : "NG", "code" : "+234", "flag" : "🇳🇬", "name" : "Nigeria"},
  { "iso3" : "NIU", "iso2" : "NU", "code" : "+683", "flag" : "🇳🇺", "name" : "Niue"},
  { "iso3" : "NFK", "iso2" : "NF", "code" : "+672", "flag" : "🇳🇫", "name" : "Norfolk Island"},
  { "iso3" : "MKD", "iso2" : "MK", "code" : "+389", "flag" : "🇲🇰", "name" : "North Macedonia"},
  { "iso3" : "MNP", "iso2" : "MP", "code" : "+1", "flag" : "🇲🇵", "name" : "Northern Mariana Islands"},
  { "iso3" : "NOR", "iso2" : "NO", "code" : "+47", "flag" : "🇳🇴", "name" : "Norway"},
  { "iso3" : "OMN", "iso2" : "OM", "code" : "+968", "flag" : "🇴🇲", "name" : "Oman"},
  { "iso3" : "PAK", "iso2" : "PK", "code" : "+92", "flag" : "🇵🇰", "name" : "Pakistan"},
  { "iso3" : "PLW", "iso2" : "PW", "code" : "+680", "flag" : "🇵🇼", "name" : "Palau"},
  { "iso3" : "PSE", "iso2" : "PS", "code" : "+970", "flag" : "🇵🇸", "name" : "Palestine"},
  { "iso3" : "PAN", "iso2" : "PA", "code" : "+507", "flag" : "🇵🇦", "name" : "Panama"},
  { "iso3" : "PNG", "iso2" : "PG", "code" : "+675", "flag" : "🇵🇬", "name" : "Papua New Guinea"},
  { "iso3" : "PRY", "iso2" : "PY", "code" : "+595", "flag" : "🇵🇾", "name" : "Paraguay"},
  { "iso3" : "PER", "iso2" : "PE", "code" : "+51", "flag" : "🇵🇪", "name" : "Peru"},
  { "iso3" : "PHL", "iso2" : "PH", "code" : "+63", "flag" : "🇵🇭", "name" : "Philippines"},
  { "iso3" : "PCN", "iso2" : "PN", "code" : "+64", "flag" : "🇵🇳", "name" : "Pitcairn Islands"},
  { "iso3" : "POL", "iso2" : "PL", "code" : "+48", "flag" : "🇵🇱", "name" : "Poland"},
  { "iso3" : "PRT", "iso2" : "PT", "code" : "+351", "flag" : "🇵🇹", "name" : "Portugal"},
  { "iso3" : "PRI", "iso2" : "PR", "code" : "+1", "flag" : "🇵🇷", "name" : "Puerto Rico"},
  { "iso3" : "QAT", "iso2" : "QA", "code" : "+974", "flag" : "🇶🇦", "name" : "Qatar"},
  { "iso3" : "REU", "iso2" : "RE", "code" : "+262", "flag" : "🇷🇪", "name" : "Réunion"},
  { "iso3" : "ROU", "iso2" : "RO", "code" : "+40", "flag" : "🇷🇴", "name" : "Romania"},
  { "iso3" : "RUS", "iso2" : "RU", "code" : "+7", "flag" : "🇷🇺", "name" : "Russia"},
  { "iso3" : "RWA", "iso2" : "RW", "code" : "+250", "flag" : "🇷🇼", "name" : "Rwanda"},
  { "iso3" : "BLM", "iso2" : "BL", "code" : "+590", "flag" : "🇧🇱", "name" : "Saint Barthélemy"},
  { "iso3" : "SHN", "iso2" : "SH", "code" : "+290", "flag" : "🇸🇭", "name" : "Saint Helena, Ascension and Tristan da Cunha"},
  { "iso3" : "KNA", "iso2" : "KN", "code" : "+1", "flag" : "🇰🇳", "name" : "Saint Kitts and Nevis"},
  { "iso3" : "LCA", "iso2" : "LC", "code" : "+1", "flag" : "🇱🇨", "name" : "Saint Lucia"},
  { "iso3" : "MAF", "iso2" : "MF", "code" : "+590", "flag" : "🇲🇫", "name" : "Saint Martin"},
  { "iso3" : "SPM", "iso2" : "PM", "code" : "+508", "flag" : "🇵🇲", "name" : "Saint Pierre and Miquelon"},
  { "iso3" : "VCT", "iso2" : "VC", "code" : "+1", "flag" : "🇻🇨", "name" : "Saint Vincent and the Grenadines"},
  { "iso3" : "WSM", "iso2" : "WS", "code" : "+685", "flag" : "🇼🇸", "name" : "Samoa"},
  { "iso3" : "SMR", "iso2" : "SM", "code" : "+378", "flag" : "🇸🇲", "name" : "San Marino"},
  { "iso3" : "STP", "iso2" : "ST", "code" : "+239", "flag" : "🇸🇹", "name" : "São Tomé and Príncipe"},
  { "iso3" : "SAU", "iso2" : "SA", "code" : "+966", "flag" : "🇸🇦", "name" : "Saudi Arabia"},
  { "iso3" : "SCT", "iso2" : "GB-SCT", "code" : "+44", "flag" : "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "name" : "Scotland"},
  { "iso3" : "SEN", "iso2" : "SN", "code" : "+221", "flag" : "🇸🇳", "name" : "Senegal"},
  { "iso3" : "SRB", "iso2" : "RS", "code" : "+381", "flag" : "🇷🇸", "name" : "Serbia"},
  { "iso3" : "SYC", "iso2" : "SC", "code" : "+248", "flag" : "🇸🇨", "name" : "Seychelles"},
  { "iso3" : "SLE", "iso2" : "SL", "code" : "+232", "flag" : "🇸🇱", "name" : "Sierra Leone"},
  { "iso3" : "SGP", "iso2" : "SG", "code" : "+65", "flag" : "🇸🇬", "name" : "Singapore"},
  { "iso3" : "SXM", "iso2" : "SX", "code" : "+1", "flag" : "🇸🇽", "name" : "Sint Maarten"},
  { "iso3" : "SVK", "iso2" : "SK", "code" : "+421", "flag" : "🇸🇰", "name" : "Slovakia"},
  { "iso3" : "SVN", "iso2" : "SI", "code" : "+386", "flag" : "🇸🇮", "name" : "Slovenia"},
  { "iso3" : "SLB", "iso2" : "SB", "code" : "+677", "flag" : "🇸🇧", "name" : "Solomon Islands"},
  { "iso3" : "SOM", "iso2" : "SO", "code" : "+252", "flag" : "🇸🇴", "name" : "Somalia"},
  { "iso3" : "ZAF", "iso2" : "ZA", "code" : "+27", "flag" : "🇿🇦", "name" : "South Africa"},
  { "iso3" : "SGS", "iso2" : "GS", "code" : "N/A", "flag" : "🇬🇸", "name" : "South Georgia"},
  { "iso3" : "SSD", "iso2" : "SS", "code" : "+211", "flag" : "🇸🇸", "name" : "South Sudan"},
  { "iso3" : "ESP", "iso2" : "ES", "code" : "+34", "flag" : "🇪🇸", "name" : "Spain"},
  { "iso3" : "LKA", "iso2" : "LK", "code" : "+94", "flag" : "🇱🇰", "name" : "Sri Lanka"},
  { "iso3" : "SDN", "iso2" : "SD", "code" : "+249", "flag" : "🇸🇩", "name" : "Sudan"},
  { "iso3" : "SUR", "iso2" : "SR", "code" : "+597", "flag" : "🇸🇷", "name" : "Suriname"},
  { "iso3" : "SJM", "iso2" : "SJ", "code" : "+47", "flag" : "🇸🇯", "name" : "Svalbard and Jan Mayen"},
  { "iso3" : "SWE", "iso2" : "SE", "code" : "+46", "flag" : "🇸🇪", "name" : "Sweden"},
  { "iso3" : "CHE", "iso2" : "CH", "code" : "+41", "flag" : "🇨🇭", "name" : "Switzerland"},
  { "iso3" : "SYR", "iso2" : "SY", "code" : "+963", "flag" : "🇸🇾", "name" : "Syria"},
  { "iso3" : "TWN", "iso2" : "TW", "code" : "+886", "flag" : "🇹🇼", "name" : "Taiwan"},
  { "iso3" : "TJK", "iso2" : "TJ", "code" : "+992", "flag" : "🇹🇯", "name" : "Tajikistan"},
  { "iso3" : "TZA", "iso2" : "TZ", "code" : "+255", "flag" : "🇹🇿", "name" : "Tanzania"},
  { "iso3" : "THA", "iso2" : "TH", "code" : "+66", "flag" : "🇹🇭", "name" : "Thailand"},
  { "iso3" : "TLS", "iso2" : "TL", "code" : "+670", "flag" : "🇹🇱", "name" : "Timor-Leste"},
  { "iso3" : "TGO", "iso2" : "TG", "code" : "+228", "flag" : "🇹🇬", "name" : "Togo"},
  { "iso3" : "TKL", "iso2" : "TK", "code" : "+690", "flag" : "🇹🇰", "name" : "Tokelau"},
  { "iso3" : "TON", "iso2" : "TO", "code" : "+676", "flag" : "🇹🇴", "name" : "Tonga"},
  { "iso3" : "TTO", "iso2" : "TT", "code" : "+1", "flag" : "🇹🇹", "name" : "Trinidad and Tobago"},
  { "iso3" : "TUN", "iso2" : "TN", "code" : "+216", "flag" : "🇹🇳", "name" : "Tunisia"},
  { "iso3" : "TUR", "iso2" : "TR", "code" : "+90", "flag" : "🇹🇷", "name" : "Turkey"},
  { "iso3" : "TKM", "iso2" : "TM", "code" : "+993", "flag" : "🇹🇲", "name" : "Turkmenistan"},
  { "iso3" : "TCA", "iso2" : "TC", "code" : "+1", "flag" : "🇹🇨", "name" : "Turks and Caicos Islands"},
  { "iso3" : "TUV", "iso2" : "TV", "code" : "+688", "flag" : "🇹🇻", "name" : "Tuvalu"},
  { "iso3" : "UGA", "iso2" : "UG", "code" : "+256", "flag" : "🇺🇬", "name" : "Uganda"},
  { "iso3" : "UKR", "iso2" : "UA", "code" : "+380", "flag" : "🇺🇦", "name" : "Ukraine"},
  { "iso3" : "ARE", "iso2" : "AE", "code" : "+971", "flag" : "🇦🇪", "name" : "United Arab Emirates"},
  { "iso3" : "GBR", "iso2" : "GB", "code" : "+44", "flag" : "🇬🇧", "name" : "United Kingdom"},
  { "iso3" : "USA", "iso2" : "US", "code" : "+1", "flag" : "🇺🇸", "name" : "United States"},
  { "iso3" : "USA", "iso2" : "UM", "code" : "+1", "flag" : "🇺🇲", "name" : "United States Minor Outlying Islands"},
  { "iso3" : "URY", "iso2" : "UY", "code" : "+598", "flag" : "🇺🇾", "name" : "Uruguay"},
  { "iso3" : "UZB", "iso2" : "UZ", "code" : "+998", "flag" : "🇺🇿", "name" : "Uzbekistan"},
  { "iso3" : "VUT", "iso2" : "VU", "code" : "+678", "flag" : "🇻🇺", "name" : "Vanuatu"},
  { "iso3" : "VAT", "iso2" : "VA", "code" : "+39", "flag" : "🇻🇦", "name" : "Vatican City (Holy See)"},
  { "iso3" : "VEN", "iso2" : "VE", "code" : "+58", "flag" : "🇻🇪", "name" : "Venezuela"},
  { "iso3" : "VNM", "iso2" : "VN", "code" : "+84", "flag" : "🇻🇳", "name" : "Vietnam"},
  { "iso3" : "VGB", "iso2" : "VG", "code" : "+1", "flag" : "🇻🇬", "name" : "British Virgin Islands"},
  { "iso3" : "VIR", "iso2" : "VI", "code" : "+1", "flag" : "🇻🇮", "name" : "United States Virgin Islands"},
  { "iso3" : "WLS", "iso2" : "GB-WLS", "code" : "+44", "flag" : "🏴󠁧󠁢󠁷󠁬󠁳󠁿", "name" : "Wales"},
  { "iso3" : "WLF", "iso2" : "WF", "code" : "+681", "flag" : "🇼🇫", "name" : "Wallis and Futuna"},
  { "iso3" : "ESH", "iso2" : "EH", "code" : "+212", "flag" : "🇪🇭", "name" : "Western Sahara"},
  { "iso3" : "YEM", "iso2" : "YE", "code" : "+967", "flag" : "🇾🇪", "name" : "Yemen"},
  { "iso3" : "ZMB", "iso2" : "ZM", "code" : "+260", "flag" : "🇿🇲", "name" : "Zambia"},
  { "iso3" : "ZWE", "iso2" : "ZW", "code" : "+263", "flag" : "🇿🇼", "name" : "Zimbabwe"},
]